name: spotnav
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.3
  http: ^1.2.1
  fpdart: ^1.1.0
  get_it: ^7.6.0
  connectivity_plus: ^6.0.1
  equatable: ^2.0.7
  logging: ^1.3.0
  gap: ^3.0.1
  extended_image: ^10.0.1
  intl: ^0.20.2
  smooth_page_indicator: ^1.2.1
  linkfy_text: ^1.1.6
  url_launcher: ^6.3.1
  flutter_staggered_grid_view: ^0.7.0
  geocoding: ^4.0.0
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  flutter_rating_bar: ^4.0.1
  go_router: ^15.1.3
  dismissible_page: ^1.0.0
  # Firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.3
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  package_rename: ^1.10.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/brands/
    - assets/images/failures/
    - assets/data/
